theme: jekyll-theme-minimal
icon-57p: "/icon/icon57.png"
icon-60p: "/icon/icon60.png"
icon-72p: "/icon/icon72.png"
icon-76p: "/icon/icon76.png"
icon-114p: "/icon/icon114.png"
icon-120p: "/icon/icon120.png"
icon-144p: "/icon/icon144.png"
icon-152p: "/icon/icon152.png"
favicon: "/icon/favicon.ico"
